Create parser for wildberries
Fox1ine/WildberriesData pull request #1
Opened 2024-08-10 00:07 UTC by Fox1ine

2024-08-10 00:20 UTC, NeoDyxXx requested changes

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +service = Service('D:/FoxDriver/geckodriver.exe')
Сделать относительный путь

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +service = Service('D:/FoxDriver/geckodriver.exe')
Помести exe файл в репу или скачивай его через библиотеку

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +headers = {
сделать отдельный файл с конфигом и поместить его туда

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +        with open("Wild.html", 'w', encoding='utf-8') as file:
зачем если ты можешь возвращать текст от html а не сохранять как файл?

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +        with open(file_path, 'rb') as file:
так же тут, можно просто принять строку с html

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +    with open("Wild.html", 'w', encoding='utf-8') as file:
опять зачем тут запись в файл?

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +    with open(fileURL_path) as file:
и тут очередное чтение

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +                print(f"Item name is - {item_name}")
не принты а logging

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +            item_name = soup.find('h1', class_="product-page__title")
сделать отдельную функцию для выборки элементы, а не тупо повторять код

2024-08-10 00:20 UTC, NeoDyxXx commented on main.py
> +    df.to_csv("result.csv", index=False, encoding='utf-8-sig')
почему такой encoding, можно просто utf-8

2024-08-10 00:35 UTC, NeoDyxXx requested changes

2024-08-10 00:35 UTC, NeoDyxXx commented on main.py
> +        driver = webdriver.Firefox(service=service, options=options)
сделай через with, чтобы не допустить ошибку если ты забудешь использовать driver.quit()

2024-08-10 00:35 UTC, NeoDyxXx commented on main.py
> +    driver = webdriver.Firefox(service=service, options=options)
тут так же через with

2024-08-10 00:43 UTC, NeoDyxXx requested changes

2024-08-10 00:43 UTC, NeoDyxXx commented on main.py
> +        time.sleep(5)
убери sleep и сделай фунции ожидания загрузки страницы из библиотеку селениум (не помню название найди сам)

2024-08-11 12:16 UTC, Fox1ine commented on main.py
> +    with open(fileURL_path) as file:
Справедливо ли это?

2024-08-11 12:17 UTC, Fox1ine commented on main.py
> +service = Service('D:/FoxDriver/geckodriver.exe')
Сделал

2024-08-18 21:22 UTC, NeoDyxXx requested changes
В некоторый моментах я просто в шоке, ну а так норм

2024-08-18 21:22 UTC, NeoDyxXx commented on .gitignore
> +.idea/discord.xml
просто добавь сюда папку .idea, не нужно указывать каждый файл из нее

2024-08-18 21:22 UTC, NeoDyxXx commented on main.py
> +                if item_name:
пхахах, логирование тоже можно в 1 функцию обернуть и просто вызывать после каждого извлечения элемента, типо:
```
def logger_value(value, message_if_exists, message_if_not_exists):
    if value:
         logger.info(message_if_exists)
    else:
         logger.warning(message_if_not_exists)
```

2024-08-18 21:22 UTC, NeoDyxXx commented on main.py
> +                        'item_url': url,
убери префикс item, будет лучше выглядеть

2024-08-18 21:22 UTC, NeoDyxXx commented on main.py
> +        logger.info("Data successfully saved to 'result.csv'")
сделай проверку создан ли файл

2024-08-18 21:22 UTC, NeoDyxXx commented on my_config.py
назови просто config, без my_

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +    df.fillna(df.mean(numeric_only=True), inplace=True)
ну ставить среднее значение конечно спорно, для данного датасета может и будет гуд, но ситуации бывают разные, допустим чтобы указать для цены товара что нет значения можно указать например -1, 0, -inf, средняя цена нужна для ML, но так же есть разные подходы для получения среднего значения, так что лучше узнавать этот момент у консумера данных

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +def clear_data(file_path):
по секрету скажу что это тоже часть дата фьючеринга)

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +    new_column_name = {
хм, менять надо было не здесь, а в скрапере....

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +# Example usage:
удали лишний комментарий

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +    # Load the Parquet file to verify its contents
записать датафрейм в паркет чтобы потом сразу его прочитать и запринтить, ты гений что-ли?????

2024-08-18 21:22 UTC, NeoDyxXx commented on pipeline.py
> +    # Load the Parquet file to verify its contents
лучше измени на проверку что файл записан

2024-08-18 21:23 UTC, NeoDyxXx commented on pipeline.py
> +    df.fillna(df.mean(numeric_only=True), inplace=True)
эт просто комментарий, ничего изменять не надо

2024-08-18 21:29 UTC, NeoDyxXx commented
мне иногда кажется что лучше бы я стал блогером по аниме, чем вот это вот все

2024-08-19 17:09 UTC, Fox1ine commented on pipeline.py
> +    df.fillna(df.mean(numeric_only=True), inplace=True)
Принял

2024-08-19 17:10 UTC, Fox1ine commented on pipeline.py
> +    new_column_name = {
Исключительно self study moment xD

2024-08-19 17:13 UTC, Fox1ine commented on pipeline.py
> +def clear_data(file_path):
Я так и понял)

2024-08-19 18:41 UTC, NeoDyxXx requested changes

2024-08-19 18:41 UTC, NeoDyxXx commented on main.py
> +            try:
проверяй что файл создан через os библиотеку, try тут не нужен

2024-08-19 18:43 UTC, NeoDyxXx requested changes

2024-08-19 18:43 UTC, NeoDyxXx commented on pipeline.py
> +    new_column_name = {
убирай его

2024-08-19 18:43 UTC, NeoDyxXx commented on pipeline.py
> +    try:
тут тоже самое

2024-08-19 18:43 UTC, NeoDyxXx commented on pipeline.py
> +if __name__ == '__main__':
зачем тебе 2 мейн функции?

2024-08-19 19:34 UTC, Fox1ine commented on pipeline.py
> +if __name__ == '__main__':
Старый коммит был, уже удалил давно

2024-08-19 20:04 UTC, NeoDyxXx requested changes

2024-08-19 20:04 UTC, NeoDyxXx commented on main.py
> +                        'name': item_name,
в названиях переменных тоже убери

2024-08-19 20:19 UTC, NeoDyxXx approved these changes

2024-08-19 20:21 UTC, merged